name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Static Web App

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId":     "${{ secrets.AZURE_TENANT_ID }}"
            }

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                 ${{ secrets.GITHUB_TOKEN }}
          action:                     upload
          app_location:               "/"       # Adjust if your app lives in a subfolder
          api_location:               "api"     # Or the folder where your Azure Functions live
          output_location:            "build"   # Your production build folder

