name: Build and Deploy SWA

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install front-end deps
        run: npm ci --prefix avd-control-pwa

      - name: Build front-end
        run: npm run build --prefix avd-control-pwa

      - name: Install API deps
        run: npm ci --prefix avd-control-pwa/api

      - name: Build API
        run: npm run build --prefix avd-control-pwa/api

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                      ${{ secrets.GITHUB_TOKEN }}
          action:                          upload
          app_location:                    "avd-control-pwa"
          api_location:                    "avd-control-pwa/api"
          output_location:                 "avd-control-pwa/build"
