# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD with Debug

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug: print cwd and full file tree
        run: |
          echo ">> PWD: $(pwd)"
          echo ">> Listing everything under here:"
          ls -R .
