name: Azure Static Web Apps CI/CD (OIDC)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    # This must match the environment you configured in Azure AD federated credentials
    environment: avd-control-pwa

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Azure Login (OIDC)
        uses: azure/login@v1
        with:
          use-github-actions-identity: true
          tenant-id:              ${{ secrets.AZURE_TENANT_ID }}
          client-id:              ${{ secrets.AZURE_CLIENT_ID }}
          allow-no-subscriptions: true

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_THANKFUL_STONE_03F4D6800 }}
          repo_token:                      ${{ secrets.GITHUB_TOKEN }}
          action:                          upload
          app_location:                    "/"        # adjust if needed
          api_location:                    "api"      # adjust if needed
          output_location:                 "build"    # adjust if needed

