# .github/workflows/azure-static-web-apps.yml
name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # FRONT-END
      - name: Install front-end dependencies
        working-directory: avd-control-pwa
        run: npm install

      - name: Build front-end
        working-directory: avd-control-pwa
        run: npm run build

      # API
      - name: Install API dependencies
        run: npm install --prefix avd-control-pwa/api

      - name: Build API
        run: npm run build --prefix avd-control-pwa/api

      - name: Deploy to Azure Static Web Apps
        uses: azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token:                      ${{ secrets.GITHUB_TOKEN }}
          action:                          upload
          app_location:                    "avd-control-pwa"
          api_location:                    "avd-control-pwa/api"
          output_location:                 "avd-control-pwa/build"
